### ISSUE TITLE
shift in the position of complete path

### ISSUE THREAD

**Issue by Botronics** [Fields2Cover/fields2cover_ros#14]
In the xml file, i have edited coordinates of my farm. But the location of the my farm is shifted completely from the original location. 
![Screenshot from 2023-01-30 16-45-52](https://user-images.githubusercontent.com/110804545/215462597-7da1e75e-d6bc-44be-b53b-5bc003967375.png)

**Comment by Botronics** [comment]
[Screenshot from 2023-01-30 16-48-27.zip](https://github.com/Fields2Cover/fields2cover_ros/files/10535232/Screenshot.from.2023-01-30.16-48-27.zip)

**Comment by Gonzalo-Mier** [comment]
Hi! Could you share the field file?

**Comment by Gonzalo-Mier** [comment]
Either way, this is probably cause due to a bad projection election. By default in the launch field, the field use the EPSG:28992 to work on meters on Netherlands. According to your picture, you should choose a transformation suitable for California. Also take into account that if you use UTM, ETRS89 is chosen by default, and can be changed if needed.

**Comment by Botronics** [comment]
> Hi! Could you share the field file?

yes.
[Screenshot from 2023-01-30 16-48-27.zip](https://github.com/Fields2Cover/fields2cover_ros/files/10542724/Screenshot.from.2023-01-30.16-48-27.zip)

**Comment by RamanaBotta** [comment]
Hi @Gonzalo-Mier ,
We are able to solve this issue by proper projection election. 
thank you

**Comment by Botronics** [comment]
Hi @Gonzalo-Mier,
Thanks for support and help.
